In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc - tic))+"ms")

c = 0

tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Non-Vectorized version:" + str(1000*(toc - tic))+"ms")

250096.030257
Vectorized version:10.529756546020508ms
250096.030257
Non-Vectorized version:679.5139312744141ms


In [4]:
a = np.random.randn(2, 3) # a.shape = (4, 3)
b = np.random.randn(2, 1) # b.shape = (3, 2)
c = np.random.randn(4,3)
B = np.sum(a, axis = 1, keepdims = True)

In [5]:
print(c.shape)

(4, 3)


In [6]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [7]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [7]:
print(c)

[[ 0.01357154  0.20339636 -0.16256171]
 [-1.20267243 -0.56094415 -0.33532987]
 [ 0.7599356  -0.15162829 -0.31283468]]


In [8]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)
